    [phases.setup]
    aptPkgs = ["libatomic1"]

    [phases.install]
    cmds = ["npm ci --omit=dev"]

    [start]
    cmd = "npm run start"

    [variables]
    NODE_VERSION = "18.17.0"
    NODE_ENV = "production" 
    NIXPACKS_PKG_MANAGERS = "npm"