    [phases.setup]
    aptPkgs = ["libatomic1"]

    [phases.install]
    cmds = ["npm install"]

    [start]
    cmd = "npm start"

    [variables]
    NODE_ENV = "production" 
    NIXPACKS_PRO_MANAGERS = "npm"